import { WorkType, CommunicationStyle, RiskTolerance, Creativity, WorkResolution, PreferredTool, PreferredStrategy, AttentionToDetail, ArtifactType, UserProfileAttributes } from "../../user_profile";
import { UserProfile } from "../../user_profile";

const a: UserProfileAttributes = {
    role: "chief of staff",
    responsibility: "manage the company",
    mbti_type: "ENTJ",
    work_type: WorkType.TACTICAL,
    attention_to_detail: AttentionToDetail.HIGH,
    communication_style: CommunicationStyle.FORMAL,
    risk_tolerance: RiskTolerance.MEDIUM,
    creativity: Creativity.MEDIUM,
    work_resolution: WorkResolution.Tactical,
    artifact_types: ['project_plan', 'project_timeline', 'project_budget', 'project_risk_management', 'project_communication_plan', 'project_resource_allocation', 'project_status_report'],
    preferred_tools: ['excel', 'powerpoint', 'notion'],
    preferred_strategies: ['eisenhower_matrix', 'time_blocking', 'pomodoro_technique'],
    key_life_experiences: ['startup', 'growth', 'scale'],
    hobbies: ['reading', 'traveling', 'cooking', 'gardening'],
    education: ['mba', 'business_administration', 'finance'],
    work_history: ['startup', 'growth', 'scale'],
    birth_date: '1995-01-01',
    gender: 'female',
    location: 'New York, NY',
    heritage: 'Danish',
    interests: ['entrepreneurship', 'finance', 'technology'],
    values: ['integrity', 'innovation', 'customer_focus'],
    gallup_strengths: ['adaptability', 'communication', 'focus'],
    predictive_index: ['self_awareness', 'empathy', 'communication'],
    disc_profile: ['dominance', 'influence', 'steadiness', 'conformity'],
    family_status: 'single',
    sleep_level: "high",
    energy_level: "medium",
    focus_level: "high",
    political_views: "moderate",
    drug_use: "recreational",
    learning_rate: "high",
    favorite_activities: ["yoga", "reading", "traveling", "spinning"],
    // @TODO - fix these

    pets: ["golden retriever"],
    children: ["daughter (15)", "son (12)"],
    religious_views: "agnostic",
    favorite_books: ["Good to Great", "Zero to One", "The Innovator's Dilemma"],
    favorite_movies: ["The Godfather", "The Social Network", "Moneyball"],
    favorite_music: ["classical", "jazz", "rock"],
    favorite_sports: ["golf", "tennis"],
    favorite_foods: ["sushi", "italian"],
    favorite_colors: ["blue", "gray"],
    favorite_animals: ["dogs", "dolphins"],
    favorite_destinations: ["Tokyo", "London", "New York"],
    key_accomplishments: ["IPO", "successful exit", "industry awards"],
    key_failures: ["failed startup", "missed market timing"],
    learning_style: "experiential",
    preferred_learning_methods: ["reading", "hands-on", "mentoring others"],
    preferred_feedback_style: "direct",
    preferred_feedback_frequency: "weekly",
    preferred_communication_style: "concise",
    preferred_meeting_style: "standing",
    key_influencers: ["Steve Jobs", "Warren Buffett", "Jeff Bezos"],
    mother: null,
    father: null,
    spouse: null,
    best_friend: null,
    mentor: null,
    role_model: null,
    parent_profile_id: null,
    emotional_state: ["emotional_stability"],
    emotional_variance: ["low"],
    motivation_level: "high",
    creativity_level: "high",
    productivity_level: "high"
}

const cos = new UserProfile("John", "Chief of Staff", a);

export default cos;

