/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import { Image } from "@boundaryml/baml"

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum EisenHowerAttribute {
  IMPORTANT = "IMPORTANT",
  NOT_IMPORTANT = "NOT_IMPORTANT",
  URGENT = "URGENT",
  NOT_URGENT = "NOT_URGENT",
}

export enum EisenHowerMatrix {
  DO_IT_NOW = "DO_IT_NOW",
  SCHEDULE_IT = "SCHEDULE_IT",
  DELEGATE_IT = "DELEGATE_IT",
  DELETE_IT = "DELETE_IT",
}

export enum ReportType {
  RESEARCH = "RESEARCH",
  REPORT = "REPORT",
  MARKET_RESEARCH = "MARKET_RESEARCH",
  UX_RESEARCH = "UX_RESEARCH",
  UX_DESIGN = "UX_DESIGN",
  UX_PROTOTYPE = "UX_PROTOTYPE",
  UX_TESTING = "UX_TESTING",
  BUSINESS_PLAN = "BUSINESS_PLAN",
  MARKETING_PLAN = "MARKETING_PLAN",
  FINANCIAL_PLAN = "FINANCIAL_PLAN",
  OPERATIONAL_PLAN = "OPERATIONAL_PLAN",
}

export enum UrgencyOptions {
  NOW = "NOW",
  MORNING = "MORNING",
  AFTERNOON = "AFTERNOON",
  EVENING = "EVENING",
  TODAY = "TODAY",
  TOMORROW = "TOMORROW",
  THIS_WEEK = "THIS_WEEK",
  NEXT_WEEK = "NEXT_WEEK",
  THIS_MONTH = "THIS_MONTH",
  NEXT_MONTH = "NEXT_MONTH",
  THIS_YEAR = "THIS_YEAR",
  NEXT_YEAR = "NEXT_YEAR",
  ANYTIME = "ANYTIME",
  UNSPECIFIED = "UNSPECIFIED",
}

export interface ReportArtifact {
  guid: string
  created_at: string
  upstringd_at: string
  creators: string[]
  name: string
  description: string
  version: number
  executive_summary: string
  
}

export interface ReportSection {
  guid: string
  created_at: string
  upstringd_at: string
  creators: string[]
  name: string
  description: string
  version: number
  section_title: string
  section_content: ReportSectionContent[]
  position: number
  
}

export interface ReportSectionContent {
  guid: string
  created_at: string
  upstringd_at: string
  creators: string[]
  name: string
  description: string
  version: number
  content: string
  
}

export interface ResearchArtifact {
  guid: string
  created_at: string
  upstringd_at: string
  creators: string[]
  name: string
  description: string
  version: number
  authors: string[]
  title: string
  content: ReportArtifact
  
}

export interface Resume {
  name: string
  email: string
  experience: string[]
  skills: string[]
  
}

export interface Task {
  guid: string
  created_at: string
  updated_at: string
  creators: string[]
  name: string
  description: string
  version: number
  task: string
  eh_importance: EisenHowerAttribute
  eh_urgency: EisenHowerAttribute
  eh_matrix: EisenHowerMatrix
  urgency: UrgencyOptions
  
}

export interface TaskList {
  guid: string
  created_at: string
  updated_at: string
  creators: string[]
  name: string
  description: string
  version: number
  tasks: Task[]
  
}
